### ISSUE TITLE
Cannot get it to compile with the lastest version of android studio

### ISSUE THREAD

**Issue by macaquinyho** [DavidBuchanan314/NXLoader#22]
[idea.log](https://github.com/DavidBuchanan314/NXLoader/files/2123838/idea.log)
It gives me gradle sync failed

**Comment by MenosGrante** [comment]
NXLoader using 27 as compile and target SDK. You log says, that you not downloaded it using Android SDK.

**Comment by macaquinyho** [comment]
I downloaded it and it still doesnt build
[idea.log](https://github.com/DavidBuchanan314/NXLoader/files/2124524/idea.log)

**Comment by MenosGrante** [comment]
Well, there were one more error. Android Studio can't download gradle wrapper for you. Have you enabled Offline work? 

Also, you have not downloaded Build Tools revision 27.0.3
`Failed to find Build Tools revision 27.0.3`

And NDK is missing too.

I think you have enabled Offline work, otherwise Android Studio should offer you to download all missing packages.

**Comment by macaquinyho** [comment]
Thank you now it works no errors whatsoever
